Library
1v4n4/library pull request #1
Opened 2021-07-05 18:47 UTC by 1v4n4

2021-07-05 19:37 UTC, trekab requested changes
### Changes Required! :recycle: 
Hi @1v4n4! So far so good! :+1: I think you made good use of the `Book` constructor and form validation to reject empty book submissions. However, there are a few changes I'd like you to work on to finally complete this project. These include:
- [x] The __new book form__ should have a provision for the user to mark the book's read status. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/new_book_button_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))
- [x] __[Optional]__ Implement data persistence by saving, retrieving, and updating the library books using [the localstorage API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/localstorage_stretch_requirement.png) from [Odin Project](https://www.theodinproject.com/courses/javascript/lessons/library))
- [ ] Please refer to the code comment below about the logic of displaying the books.

_Please make the necessary changes and submit another code review request._
__[Treasure Kabareebe](https://trekab.github.io)__

2021-07-05 19:37 UTC, trekab commented on index.js
> +}
:thinking: It appears that your approach differs from the expected implementation. Please note that you are expected to loop through the books array to display each book. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/books_render_loop.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))

2021-07-06 10:38 UTC, 1v4n4 commented on index.js
> +}
well, now I needed that method to display books from local storage, so it is done

2021-07-06 11:12 UTC, mimipeshy commented
## STATUS: APPROVED 🥳 👯 
Hello team @1v4n4 👋🏾 👋🏾 congratulations on making it this far in this milestone 🥇 

#### Highlights
- You have worked on all changes requested by the previous TSE ✔️ 

With that, I approve of this project 😄 

Regards
__Peris Ndanu __
[GitHub ](https://github.com/mimipeshy)| [LinkedIn ](https://www.linkedin.com/in/peris-ndanu/)| [Twitter](https://twitter.com/pygirl254)

2021-07-06 11:14 UTC, merged